### ISSUE TITLE
Possibly set up a json dictionary based on classes of rates?

### ISSUE THREAD

**Issue by monkeywithacupcake** [bwigianto/powertochoose#10]
I'm thinking that we could save the tariff and a link and separate out different charges and such with a JSON dictionary. We could seed it with classes of TDU.

For example (made up data):
```
class rate(object):
    def __init__(self, lim, func):
        self.lim = lim,
        self.func = func
tier = rate(500, '(.05)*(x-500)') # example to show is object
print(tier)

class TDU(object):
    def __init__(self, name, tariff, base, tier1, tier2, tier3):
        self.name = name
        self.tariff = tariff,
        self.base = base,
        self.tier1 = tier1,
        self.tier2 = tier2,
        self.tier3 = tier3
infuse = TDU('infuse_3', 'abc123-10abcd-ef', '10',
            rate(500, '(.05)*(x-500)'), 
            rate(1500, '(.05)*(x-1500)'), 
            rate(2500, '(.10)*(x-2500)'))
print(infuse) # example to show nesting rate in TDU

def jdefault(o):
    return o.__dict__
print(json.dumps(infuse, default=jdefault))
# prints json representation (which is what we would store)
```
These are the print outputs FYI
```
<__main__.rate object at 0x015CA930>
<__main__.TDU object at 0x015CAB90>
{"base": ["10"], "tier2": [{"lim": [1500], "func": "(.05)*(x-1500)"}], "tier1": [{"lim": [500], "func": "(.05)*(x-500)"}], "tier3": {"lim": [2500], "func": "(.10)*(x-2500)"}, "tariff": ["abc123-10abcd-ef"], "name": "infuse_3"}
```

On the backend, then, we create a function that reads the json files and evals the rates?

**Comment by bwigianto** [comment]
Good thoughts! One complication I can think of is that different companies have different cutoffs for their usage tiers. Some use 1000kWh, 1250kWh, others 1500kWh. And they keep changing it. We could parameterize that, but then I could imagine the retailer adding an additional tier.
The main reason I made the logic of the existing functions really simple is to learn and classify different kinds of plans before coming up with a generic model. The retailers' goal is to make coming up with this generic model very difficult if not impossible

**Comment by monkeywithacupcake** [comment]
I agree that it is complicated, that is why I thought the tier's would be set for each one, so maybe the class could have any number of tiers/rates? This is already defined to allow for different cutoffs for each one, so even with the TDU class defined as above, we could have something like:
```
infuse3 = TDU('infuse_3', 'abc123-10abcd-ef', '10',
            rate(500, '(.05)*(x-500)'), 
            rate(1500, '(.05)*(x-1500)'), 
            rate(2500, '(.10)*(x-2500)'))
infuse6 = TDU('infuse_6', 'abc123-10abcxxd-ef', '100',
            rate(500, '(.05)*(x-500)'), 
            rate(1500, '(.07)*(x-1000)'), 
            rate(2500, '(.03)*(x-1900)'))
other_co_other_rate = TDU('other_co_other_rate', 'sss123-10abcd-ef', '200',
            rate(999, '(.05)*(x)'), 
            rate(1400, '(.07)*(x-999)'), 
            rate(2000, '(.07)*(500) + (.03)*(x-1400)'))
```

**Comment by monkeywithacupcake** [comment]
I guess the class should include a url (to the fact sheet) and perhaps the company name separate. That way, it would be easier to pull out all the ones that belong in groups and produce usable data?

**Comment by bwigianto** [comment]
Sorry, you're right, I wasn't looking at that closely. What's the proper way for a plan with only two tiers?
![image](https://user-images.githubusercontent.com/3519524/31322939-9ba95236-ac65-11e7-8ca4-83eb9411adbf.png)

**Comment by monkeywithacupcake** [comment]
I just made a PR with a setup classes. It would look like this: 
```
example = Offer('example_name', 'utility', 'some tariff ref','url.com', '100',
            [Tier(0, 'base'), # or 0, I'm not sure without rest of context, doubt "free"
            Tier(1000, '100 + (.13)*(x-1000)')])
```

**Comment by monkeywithacupcake** [comment]
Same link from the PR for setup class, but I think it may help this discussion: This is a playground showing how the Offer class works. https://code.sololearn.com/cAo2FlACcLpq/#py

**Comment by monkeywithacupcake** [comment]
I'm closing this because there is a separate PR and discussion. That way, we can keep the discussion in one place.
