### ISSUE TITLE
Have python script actually call all billing functions and return dictionaries of estimates

### ISSUE THREAD

**Issue by bwigianto** [bwigianto/powertochoose#3]
## Feature
Make houston.py call all functions inside and return the sum of total bills

## Why is this feature being added?
The houston.py file is all hard coded with my example usage pattern over a 12 month period and so it's not generally useful yet.

## What should your feature do?
When I run the script with 12 numbers 
```bash
python houston.py 100 200 300 400 500 600 700 800 900 1000 1100 1200 
```
we get a dictionary of plan names (function names) to total price over the 12 month period:
```python
{'keep it simple savings': 210.34, 'wise buy complete': 120.54 ... }
```

**Comment by kevinah95** [comment]
Can I take this?

**Comment by bwigianto** [comment]
Yes @kevinah95 go for it!
